---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-test
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::543987887526:role/talant-oidc-sa-role"

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: testpod
  name: testpod
spec:
  serviceAccountName: aws-test
  containers:
  - image: amazon/aws-cli
    name: testpod
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 30; done"]

